-- Migration: V2__create_users_table.sql
-- Purpose: Create users table for authentication and user management
-- Security: Store hashed passwords only, use unique index on username

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    description VARCHAR(255),
    CONSTRAINT chk_role CHECK (role IN ('ROLE_ADMIN', 'ROLE_AUDIT_WRITER', 'ROLE_AUDIT_READER'))
);

-- Indexes for performance
CREATE INDEX idx_username ON users(username);
CREATE INDEX idx_active ON users(active);
CREATE INDEX idx_role ON users(role);

-- Insert default admin user (password: admin123)
INSERT INTO users (username, password_hash, role, active, created_by, description)
VALUES ('admin', '$2a$10$Kanho2FwjlMoGQ9JK/m.5e5eK1FVo1/v6n7K3NtUu3rp.H5.8WVLe', 'ROLE_ADMIN', TRUE, 'SYSTEM', 'Default admin user');

-- Insert default writer user (password: writer123)
INSERT INTO users (username, password_hash, role, active, created_by, description)
VALUES ('writer', '$2a$10$SFTrJdrrDFYPnuTm5DT78.caPmR/LmxE4cRgBCaqp.W6Av7yR361m', 'ROLE_AUDIT_WRITER', TRUE, 'SYSTEM', 'Default writer user');

-- Insert default reader user (password: reader123)
INSERT INTO users (username, password_hash, role, active, created_by, description)
VALUES ('reader', '$2a$10$5xUw/2tX0axh5EoIaKTkT.bECIOXa9H08.4WQrn.Qh9n35oGtC92m', 'ROLE_AUDIT_READER', TRUE, 'SYSTEM', 'Default reader user');
